"""init

Revision ID: 0d741bc2513a
Revises: 
Create Date: 2023-10-20 20:02:39.961220

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0d741bc2513a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=False),
        sa.Column("packing", sa.Integer(), nullable=True),
        sa.Column(
            "size",
            sa.Enum("SMALL", "BIG", "HUGE", "TWO_IN_A_BIG", name="productsize"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
